demoapp/urls.py
from django.urls import path, re_path

from . import views

app_name = 'demoapp'
urlpatterns = [
    path('', views.app_home, name='app_home'),
    #Using function view same result as CompanyListView CBV
    #path('company/', views.company_list, name='company_list'),
    # Using Class Based View
    path('company/', views.CompanyView.as_view(), name='company_list'),
    # Using generic Class Based View
    #path('company/', views.CompanyListView.as_view(), name='company_list'),
    path('company/<int:pk>/', views.CompanyDetailView.as_view(), name='company_detail'),
    path('company/create/', views.CompanyCreateView.as_view(), name='company_create'),
    path('company/<int:pk>/update', views.CompanyUpdateView.as_view(), name='company_update'),
    path('company/<int:pk>/delete', views.CompanyDeleteView.as_view(), name='company_delete'),
    #Employee URL's
    path('employee/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employee/create/', views.EmployeeCreateView.as_view(), name='employee_create'),
    path('employee/<int:pk>/update', views.EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete', views.EmployeeDeleteView.as_view(), name='employee_delete'),

]

demoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def redirect_root(request):
    return redirect('demoapp:app_home', permanent=True)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demoapp/', include('demoapp.urls')),
    path('', redirect_root)
]

demoapp/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Company(models.Model):
    """
    Model for Company information
    """
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('demoapp:company_detail', kwargs={'pk': self.pk})

class Employee(models.Model):
    """
    Model for Employee information
    """
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    address = models.CharField(max_length=64, blank=True)
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=32, blank=True)
    zip_code = models.CharField(max_length=10, blank=True)

    def __str__(self):
        return str(self.first_name) + ' ' + str(self.last_name)

    def get_absolute_url(self):
        return reverse('demoapp:employee_detail', kwargs={'pk': self.pk})

demoapp/forms.py
from django.forms import ModelForm, Form

from .models import Employee

class EmployeeForm(ModelForm):

    class Meta:
        model = Employee
        fields = '__all__'

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        return data.title()

    def clean_last_name(self):
        data = self.cleaned_data['last_name']
        return data.title()

demoapp/views.py
from django.shortcuts import render, HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView, DeleteView

from .models import Company, Employee
from .forms import EmployeeForm
# Create your views here.

def index(request):
    return HttpResponse('Yay I made a request return http response')


def app_home(request):
    return render(request, 'demoapp/base_demoapp.html')


#company list function view
def company_list(request):
    companies = Company.objects.all()
    context = {'object_list': companies}
    return render(request, 'demoapp/company_list.html', context=context)


#company list class based view
class CompanyView(View):

    def get(self, request):
        companies = Company.objects.all()
        context = {'object_list': companies}
        return render(request, 'demoapp/company_list.html', context=context)


#company list generic class based view
class CompanyListView(ListView):
    model = Company


class CompanyDetailView(DetailView):
    model = Company


class CompanyCreateView(CreateView):
    model = Company
    fields = '__all__'


class CompanyUpdateView(UpdateView):
    model = Company
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #so we can use the same form as create, but change create button text to update
        context['is_update'] = True
        return context


class CompanyDeleteView(DeleteView):
    model = Company
    success_url = reverse_lazy('demoapp:company_list')


class EmployeeDetailView(DetailView):
    model = Employee


class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm


class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name_suffix = '_update_form'


class EmployeeDeleteView(DeleteView):
    model = Employee
    success_url = reverse_lazy('demoapp:company_list')

demoapp/templates/demoapp/base_demoapp.html
{% extends "base.html" %}
{% block app %}
  <h3><a href="{% url 'demoapp:app_home' %}">Demo App</a></h3>
  <a href="{% url 'demoapp:company_list' %}">Companies</a>
{% endblock %}

demoapp/templates/demoapp/company_confirm_delete.html
<button onclick="history.back();">Back</button>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

demoapp/templates/demoapp/company_detail.html
{% extends "demoapp/base_demoapp.html" %}
{% block content %}
  <button onclick="history.back();">Back</button>
      {# object is the variable used by DetailView #}
  <h3>{{ object }}</h3>
  <a href="{% url 'demoapp:company_update' object.pk %}">Edit</a>
  <a href="{% url 'demoapp:company_delete' object.pk %}">Delete</a>
<ul>
  {# object_list is the list variable used by ListView #}
  {{ object }} Employee's:
  {% for employee in object.employee_set.all %}
      <li>
        <a href="{{ employee.get_absolute_url }}">{{ employee.first_name }} {{ employee.last_name }}</a>
      </li>
  {% endfor %}

</ul>
{% endblock %}

demoapp/templates/demoapp/company_form.html
<button onclick="history.back();">Back</button>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
  {% if is_update %}
    <input type="submit" value="Update">
  {% else %}
    <input type="submit" value="Create">
  {% endif %}
</form>

demoapp/templates/demoapp/company_list.html
{% extends "demoapp/base_demoapp.html" %}
{% block content %}
  <h3>Company's:</h3>
<ul>

<a href="{% url 'demoapp:company_create' %}">Add Company</a>
<a href="{% url 'demoapp:employee_create' %}">Add Employee</a>
  {# object_list is the list variable used by ListView #}
  {% for company in object_list %}
    <li>
{#      <a href="{% url 'demoapp:company_detail' company.pk %}">{{ company.name }}</a>#}
      <a href="{{ company.get_absolute_url }}">{{ company.name }}</a>
      <ul>
        {% for employee in company.employee_set.all %}
          <li>
            {{ employee.first_name }} {{ employee.last_name }}
          </li>
        {% endfor %}
      </ul>
    </li>
  {% endfor %}
</ul>
{% endblock %}

demoapp/templates/demoapp/employee_confirm_delete.html
<button onclick="history.back();">Back</button>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

demoapp/templates/demoapp/employee_detail.html
{% extends "demoapp/base_demoapp.html" %}
{% block content %}
  <button onclick="history.back();">Back</button>
      {# object is the variable used by DetailView #}
  <h3>{{ object }}</h3>
  <a href="{% url 'demoapp:employee_update' object.pk %}">Edit</a>
  <a href="{% url 'demoapp:employee_delete' object.pk %}">Delete</a>
  <br>

  {# object_list is the list variable used by ListView #}
  {{ object }} works for {{ object.company }}


{% endblock %}

demoapp/templates/demoapp/employee_form.html
<button onclick="history.back();">Back</button>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

demoapp/templates/demoapp/employee_update_form.html
<button onclick="history.back();">Back</button>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      DemoProject
    {% endblock %}
  </title>
</head>
<body>
{% block app %}
{% endblock %}
{% block content %}
  This is the content for the base file and you will see this if its not overridden!
  If block content tag is used in child template it will override contents inside the block
{% endblock %}
</body>
</html>